// Color variables - base color palette
export const colorVariables = {
  /* frequently used */
  // grayscale
  neutral_0: '#FFFFFF',
  neutral_50: '#FAFAFA',
  neutral_100: '#F5F5F5',
  neutral_150: '#F2F2F2',
  neutral_200: '#E5E5E5',
  neutral_300: '#D4D4D4',
  neutral_400: '#A3A3A3',
  neutral_500: '#A3A3A3',
  neutral_600: '#525252',
  neutral_700: '#404040',
  neutral_800: '#262626',
  neutral_900: '#171717',
  neutral_950: '#0A0A0A',
  neutral_850: '#0F0D0D',
  neutral_550: '#676767',
  // semantic--error
  red_50: '#FEF2F2',
  red_100: '#FEE2E2',
  red_200: '#FECACA',
  red_300: '#FCA5A5',
  red_400: '#F87171',
  red_500: '#EF4444',
  red_600: '#DC2626',
  red_700: '#B91C1C',
  red_800: '#991B1B',
  red_900: '#7F1D1D',
  red_950: '#450A0A',
  // semantic--warning
  yellow_50: '#FEFCE8',
  yellow_100: '#FEF9C3',
  yellow_200: '#FEF08A',
  yellow_300: '#FDE047',
  yellow_400: '#FACC15',
  yellow_500: '#EAB308',
  yellow_600: '#CA8A04',
  yellow_700: '#A16207',
  yellow_800: '#854D0E',
  yellow_900: '#713F12',
  yellow_950: '#422006',
  // semantic--success
  emerald_50: '#ECFDF5',
  emerald_100: '#D1FAE5',
  emerald_200: '#A7F3D0',
  emerald_300: '#6EE7B7',
  emerald_400: '#34D399',
  emerald_500: '#10B981',
  emerald_600: '#059669',
  emerald_700: '#047857',
  emerald_800: '#065F46',
  emerald_900: '#064E3B',
  emerald_950: '#022C22',
  // accent--blue
  blue_50: '#EFF6FF',
  blue_100: '#DBEAFE',
  blue_200: '#BFDBFE',
  blue_300: '#93C5FD',
  blue_400: '#60A5FA',
  blue_500: '#3B82F6',
  blue_600: '#2563EB',
  blue_700: '#1D4ED8',
  blue_800: '#1E40AF',
  blue_900: '#1E3A8A',
  blue_950: '#172554',
  // accent--orange
  orange_50: '#FFF7ED',
  orange_100: '#FFEDD5',
  orange_200: '#FED7AA',
  orange_300: '#FDBA74',
  orange_400: '#FB923C',
  orange_500: '#F97316',
  orange_600: '#EA580C',
  orange_700: '#C2410C',
  orange_800: '#9A3412',
  orange_900: '#7C2D12',
  orange_950: '#431407',
  // accent--green
  green_50: '#F0FDF4',
  green_100: '#DCFCE7',
  green_200: '#BBF7D0',
  green_300: '#86EFAC',
  green_400: '#4ADE80',
  green_500: '#22C55E',
  green_600: '#16A34A',
  green_700: '#15803D',
  green_800: '#166534',
  green_900: '#14532D',
  green_950: '#052E16',
  // brand colors
  brand_50: '#ECFDF5',
  brand_100: '#D1FAE5',
  brand_200: '#A7F3D0',
  brand_300: '#6EE7B7',
  brand_400: '#34D399',
  brand_500: '#10B981',
  brand_600: '#059669',
  brand_700: '#047857',
  brand_800: '#065F46',
  brand_900: '#064E3B',
  brand_950: '#022C22',
  // grey colors
  grey_0: '#FFFFFF',
  grey_25: '#FCFCFC',
  grey_50: '#FAFAFA',
  grey_100: '#F5F5F5',
  grey_200: '#E5E5E5',
  grey_300: '#D4D4D4',
  grey_400: '#A3A3A3',
  grey_500: '#737373',
  grey_600: '#525252',
  grey_700: '#404040',
  grey_800: '#262626',
  grey_900: '#171717',
  grey_950: '#0A0A0A',
  grey_black: '#000000',
  // alert colors
  alert_success_500: '#10B981',
  alert_success_700: '#047857',
  alert_warning_500: '#F59E0B',
  alert_warning_700: '#D97706',
  alert_error_500: '#EF4444',
  alert_error_700: '#DC2626',
};

export type ColorTypes = typeof LIGHT_COLORS;

// Theme colors
const LIGHT_COLORS = {
  button: {
    text: colorVariables.neutral_0,
    /// Primary
    primary: colorVariables.brand_800,
    primaryPressed: colorVariables.emerald_800,
    primaryBorder: colorVariables.emerald_800,
    primaryText: colorVariables.neutral_0,
    primaryDisabled: colorVariables.neutral_300,
    primaryDisabledText: colorVariables.neutral_500,
    /// Secondary
    secondary: 'transparent',
    secondaryPressed: colorVariables.neutral_100,
    secondaryBorder: colorVariables.neutral_300,
    secondaryText: colorVariables.neutral_900,
    secondaryDisabled: colorVariables.neutral_0,
    secondaryDisabledText: colorVariables.neutral_300,
    secondaryDisabledBorder: colorVariables.neutral_300,
    /// Destructive
    destructive: colorVariables.neutral_0,
    destructivePressed: colorVariables.neutral_100,
    destructiveText: colorVariables.red_700,
    destructiveBorder: colorVariables.neutral_300,
    destructiveDisabled: colorVariables.neutral_0,
    destructiveDisabledBorder: colorVariables.neutral_300,
    destructiveDisabledText: colorVariables.red_300,
    /// Underline
    underlineText: colorVariables.neutral_900,
    underlineDisabledText: colorVariables.neutral_500,
  },
  iconButton: {
    /// Primary
    primary: colorVariables.neutral_0,
    primaryPressed: colorVariables.neutral_100,
    primaryBorder: colorVariables.neutral_200,
    primaryDisabled: colorVariables.neutral_300,
    primaryDisabledIcon: colorVariables.neutral_500,
    primaryDisabledBorder: colorVariables.neutral_300,
    /// Secondary
    secondary: 'transparent',
    secondaryPressed: colorVariables.neutral_100,
    secondaryBorder: colorVariables.neutral_300,
    secondaryDisabled: 'transparent',
    secondaryDisabledBorder: colorVariables.neutral_300,
    secondaryDisabledIcon: colorVariables.neutral_300,
    secondaryDisabledText: colorVariables.neutral_300,
    /// Ghost
    ghost: 'transparent',
    ghostPressed: colorVariables.neutral_200,
    ghostBorder: 'transparent',
    ghostDisabled: 'transparent',
    ghostDisabledIcon: colorVariables.neutral_300,
  },
  toggleSwitch: {
    toggle: colorVariables.neutral_0,
    toggleBg: colorVariables.neutral_300,
    toggleBgOn: colorVariables.brand_700,
    toggleDisabled: colorVariables.neutral_200,
    toggleLabel: colorVariables.neutral_950,
  },
  toggleContained: {
    bg: colorVariables.neutral_0,
  },
  radioButton: {
    label: colorVariables.neutral_950,
    circle: colorVariables.neutral_200,
    circleSelected: colorVariables.emerald_400,
    labelSelected: colorVariables.neutral_900,
    /// base
    baseBg: 'transparent',
    baseBorder: 'transparent',
    /// selected
    selectedBg: 'transparent',
    selectedBorder: 'transparent',
    /// disabled
    disabledBg: 'transparent',
    disabledBorder: 'transparent',
    disabledCircleOuter: colorVariables.neutral_200,
    disabledText: colorVariables.neutral_300,
    /// Outer circle
    outerCircleSelected: colorVariables.neutral_900,
    outerCircleUnselected: colorVariables.neutral_500,
    /// Inner circle
    innerCircleSelected: colorVariables.neutral_900,
  },
  checkbox: {
    checkMark: colorVariables.neutral_50,
    label: colorVariables.neutral_900,
    disabledLabel: colorVariables.neutral_400,
    borderBox: colorVariables.neutral_900,
    borderBoxDisabled: colorVariables.neutral_300,
  },
  otpInput: {
    borderHighlight: colorVariables.emerald_600,
    border: colorVariables.neutral_300,
    backgroundColor: colorVariables.neutral_100,
    backgroundHighlight: colorVariables.neutral_50,
  },
  background: {
    brand: colorVariables.brand_100,
    primary: colorVariables.neutral_0,
    secondary: colorVariables.neutral_100,
  },
  text: {
    primary: colorVariables.neutral_800,
    secondary: colorVariables.neutral_600,
    highlight: colorVariables.emerald_400,
    link: colorVariables.blue_700,
    danger: colorVariables.neutral_0,
  },
  input: {
    background: colorVariables.neutral_0,
    placeholder: colorVariables.neutral_500,
    border: colorVariables.neutral_300,
    textColor: colorVariables.neutral_900,
  },
};

const DARK_COLORS: ColorTypes = {
  button: {
    text: colorVariables.neutral_0,
    /// Primary
    primary: colorVariables.brand_800,
    primaryPressed: colorVariables.emerald_800,
    primaryBorder: colorVariables.emerald_800,
    primaryText: colorVariables.neutral_950,
    primaryDisabled: colorVariables.neutral_500,
    primaryDisabledText: colorVariables.neutral_700,
    /// Secondary
    secondary: 'transparent',
    secondaryPressed: colorVariables.neutral_700,
    secondaryText: colorVariables.neutral_50,
    secondaryBorder: colorVariables.neutral_600,
    secondaryDisabled: 'transparent',
    secondaryDisabledText: colorVariables.neutral_600,
    secondaryDisabledBorder: colorVariables.neutral_600,
    /// Destructive
    destructive: colorVariables.neutral_0,
    destructivePressed: colorVariables.neutral_700,
    destructiveText: colorVariables.red_600,
    destructiveBorder: colorVariables.neutral_600,
    destructiveDisabledBorder: colorVariables.neutral_600,
    destructiveDisabled: colorVariables.neutral_300,
    destructiveDisabledText: colorVariables.neutral_500,
    /// Underline
    underlineText: colorVariables.neutral_900,
    underlineDisabledText: colorVariables.neutral_500,
  },
  iconButton: {
    /// Primary
    primary: colorVariables.emerald_950,
    primaryPressed: 'transparent',
    primaryBorder: colorVariables.emerald_900,
    primaryDisabled: colorVariables.neutral_800,
    primaryDisabledIcon: colorVariables.neutral_600,
    primaryDisabledBorder: colorVariables.neutral_800,
    /// Secondary
    secondary: 'transparent',
    secondaryPressed: colorVariables.neutral_700,
    secondaryBorder: colorVariables.neutral_50,
    secondaryDisabled: 'transparent',
    secondaryDisabledBorder: colorVariables.neutral_600,
    secondaryDisabledIcon: colorVariables.neutral_600,
    secondaryDisabledText: colorVariables.neutral_500,
    /// Ghost
    ghost: 'transparent',
    ghostPressed: colorVariables.neutral_700,
    ghostBorder: 'transparent',
    ghostDisabled: 'transparent',
    ghostDisabledIcon: colorVariables.neutral_600,
  },
  toggleSwitch: {
    toggle: colorVariables.neutral_0,
    toggleBg: colorVariables.neutral_700,
    toggleBgOn: colorVariables.brand_800,
    toggleDisabled: colorVariables.neutral_200,
    toggleLabel: colorVariables.neutral_200,
  },
  toggleContained: {
    bg: colorVariables.neutral_900,
  },
  radioButton: {
    label: colorVariables.neutral_50,
    circle: colorVariables.neutral_50,
    circleSelected: colorVariables.neutral_50,
    labelSelected: colorVariables.neutral_0,
    /// base
    baseBg: 'transparent',
    baseBorder: 'transparent',
    /// selected
    selectedBg: 'transparent',
    selectedBorder: 'transparent',
    /// disabled
    disabledBg: 'transparent',
    disabledCircleOuter: colorVariables.neutral_600,
    disabledBorder: 'transparent',
    disabledText: colorVariables.neutral_600,
    /// Outer circle
    outerCircleSelected: colorVariables.neutral_50,
    outerCircleUnselected: colorVariables.neutral_500,
    /// Inner circle
    innerCircleSelected: colorVariables.neutral_50,
  },
  checkbox: {
    checkMark: colorVariables.neutral_900,
    label: colorVariables.neutral_50,
    borderBox: colorVariables.neutral_50,
    disabledLabel: colorVariables.neutral_600,
    borderBoxDisabled: colorVariables.neutral_600,
  },
  otpInput: {
    borderHighlight: colorVariables.emerald_600,
    border: colorVariables.neutral_400,
    backgroundColor: colorVariables.neutral_800,
    backgroundHighlight: colorVariables.neutral_900,
  },
  background: {
    brand: colorVariables.brand_500,
    primary: colorVariables.neutral_900,
    secondary: colorVariables.neutral_800,
  },
  text: {
    primary: colorVariables.neutral_100,
    secondary: colorVariables.neutral_500,
    highlight: colorVariables.emerald_400,
    link: colorVariables.blue_400,
    danger: colorVariables.neutral_950,
  },
  input: {
    background: colorVariables.neutral_800,
    placeholder: colorVariables.neutral_500,
    border: colorVariables.neutral_700,
    textColor: colorVariables.neutral_0,
  },
};

export { DARK_COLORS, LIGHT_COLORS };
